### ISSUE TITLE
Customize the graphics

### ISSUE THREAD

**Issue by Angelk90** [react-native-vietnam/react-native-swipe-up-down#1]
@agiletechvn, @minhchienwikipedia : 
Hi, congratulations on the project. It would be possible to have an example with graphics similar to this:
![](https://i.imgur.com/ufHopg2.gif)

**Comment by minhchienwikipedia** [comment]
Great.! I'll do it in the next version :D

**Comment by minhchienwikipedia** [comment]
@Angelk90  I had to update the new version. You can get the latest version to use it. Remember read README.md to know it :D

**Comment by Angelk90** [comment]
@minhchienwikipedia : 
You could try this example on expo on android, strange things happen.

After putting a marginTop 25 to container and doing the following movements.

First full, then mini.
The words "welcome to react native!" it does not read well.

P.Š.
You could add the following features:
1) The opacity in the background in SwipeUpDown.
2) The possibility of being able to block it at half height or at a specific height percentage as shown in the image.
https://snack.expo.io/B1ruIXVv7
