### ISSUE TITLE
ScrollView into SwipeUpDown

### ISSUE THREAD

**Issue by musmastour** [react-native-vietnam/react-native-swipe-up-down#11]
Can we add a ScrollView into your SwipeUpDown view ?

**Comment by zenVentzi** [comment]
Currently I am trying to implement a FlatList inside but it seems problematic since the scorll gets detected by SwipeUpDown component and it takes over the conrtol, closing the "Modal".

**Comment by hbarylskyi** [comment]
@musmastour @zenVentzi did any of you found some solution for that? or other library? since this one seems abandoned.

**Comment by zenVentzi** [comment]
@hbarylskyi https://www.npmjs.com/package/rn-sliding-up-panel that's the closest best I found

**Comment by hbarylskyi** [comment]
@zenVentzi thank you! will check that out.

**Comment by sairam-405** [comment]
Hi any find solution for this?
