### ISSUE TITLE
How to close the this component?

### ISSUE THREAD

**Issue by karanpratapsingh** [react-native-vietnam/react-native-swipe-up-down#12]
The component works fine, but when I swipe down to close the component, nothing happens

**Comment by Luckygirlllll** [comment]
I have the same problem, did you find a solution?

**Comment by karanpratapsingh** [comment]
No unfortunately, if I remember I went with react-native-modalize or https://github.com/osdnk/react-native-reanimated-bottom-sheet

**Comment by Luckygirlllll** [comment]
@karanpratapsingh many thanks, I will check these libraries!

**Comment by minhchienwikipedia** [comment]
Let's check the latest version 
https://github.com/react-native-vietnam/react-native-swipe-up-down/releases/tag/v1.1.3
