### ISSUE TITLE
Change swipe icon color

### ISSUE THREAD

**Issue by harrisonlo** [react-native-vietnam/react-native-swipe-up-down#14]
Can we change the swipe icon color? 🙂 I want to have the background white so the icon has to be some other color...

**Comment by developmentmoon31** [comment]
> Can we change the swipe icon color? 🙂 I want to have the background white so the icon has to be some other color...

yes possible, you have to change image in library with other color which one you want(swipicon is in image in library)

**Comment by trinhhien272** [comment]
I have same problem too,
Cannot use white background.

**Comment by buraksahin59** [comment]
Hi,
You should change it by yourself on `/node_modules/react-native-swipe-up-down/src/assets/image/`

**Comment by oscarigarcia** [comment]
@buraksahin59  I don't think it's ideal, since node_modules are not regularly uploaded to production, so the change is not feasible, however the component has an "activeDotColor" props

**Comment by minhchienwikipedia** [comment]
@harrisonlo Let's try the latest version, we also have `iconSize` and `iconColor` prop.
