### ISSUE TITLE
Move Up Move Down

### ISSUE THREAD

**Issue by Filip350** [react-native-vietnam/react-native-swipe-up-down#15]
Hey in the **usage** section is showed this code:
```
import SwipeUpDown from 'react-native-swipe-up-down';
 
// TODO: What to do with the module?
<SwipeUpDown		
    itemMini={<ItemMini />} // Pass props component when collapsed
    itemFull={<ItemFull />} // Pass props component when show full
    onShowMini={() => console.log('mini')}
    onShowFull={() => console.log('full')}
    onMoveDown={() => console.log('down')}
    onMoveUp={() => console.log('up')}
    disablePressToShow={false} // Press item mini to show full
    style={{ backgroundColor: 'green' }} // style for swipe
/>
```
And there are options: onMoveDown and onMoveUp, but i didn't found this coded options in your repositorium, and when i swiping up and down i dont get logs 'up' and 'down'.

**Comment by minhchienwikipedia** [comment]
Sorry, we don't support `onMoveDown` and `onMoveUp` anymore!
Let's check the latest version!
https://github.com/react-native-vietnam/react-native-swipe-up-down/releases/tag/v1.1.3
