### ISSUE TITLE
TextInput inside the SwipeUpDown doesn't get focus

### ISSUE THREAD

**Issue by safwan-moha** [react-native-vietnam/react-native-swipe-up-down#16]

**Comment by safwan-moha** [comment]
I fixed this. Shall I add a Pull request?

**Comment by rohitkum28** [comment]
@safwan-moha I am facing the same issue. Did you add a pull request? If not can you share how you fixed it?

**Comment by minhchienwikipedia** [comment]
@safwan-moha You can create a new pull request, I'll check it and merge it
