### ISSUE TITLE
alignment issue on itemMini

### ISSUE THREAD

**Issue by theZulqarnain** [react-native-vietnam/react-native-swipe-up-down#17]
I'm using in the notch phone,if i disable notch then also I'm getting space at the bottom in **itemMini**.can you check what is the exact problem.I'm using [this](https://snack.expo.io/B1ruIXVv7) example.

if i change the value in **showMini** function of `this.customStyle.style.top = itemMini
      ? DEVICE_HEIGHT - this.SWIPE_HEIGHT
      : DEVICE_HEIGHT;`  to `this.customStyle.style.top = 0` it working fine in notch phone(without notch option) but not in normal screen phones.

![Screenshot_2019-09-10-22-43-16-423_host exp exponent](https://user-images.githubusercontent.com/22368028/64635109-8b22d780-d41c-11e9-8027-3a67a5aed627.jpg)

**Comment by minhchienwikipedia** [comment]
Hi, can you check it on the latest version
