### ISSUE TITLE
Button inside itemFull can't be touched

### ISSUE THREAD

**Issue by jaewonha** [react-native-vietnam/react-native-swipe-up-down#18]
according https://github.com/facebook/react-native/issues/3082 at meznaric's comment
above is handled w/ below code at example/App.js

at componentWillMount 56 line
onMoveShouldSetPanResponder: this._onMoveShouldSetPanResponder,

declare function as
_onMoveShouldSetPanResponder = (event, gestureState) => {
    console.log('_onMoveShouldSetPanResponder', gestureState.dx, gestureState.dy);
    return !(Math.abs(gestureState.dx) < 5 && Math.abs(gestureState.dy) < 5);
  };

**Comment by jaewonha** [comment]
fixed with above code, tested on android device & ios emulator

**Comment by jaewonha** [comment]
Hope someone fix this issue and with code described above. (index.js inside module and should add textbutton toggle ui at example)

**Comment by rohitkum28** [comment]
@jaewonha Did you raise a pull request for this? They should make the above suggested changes.

**Comment by jaewonha** [comment]
thanks. did here https://github.com/react-native-vietnam/react-native-swipe-up-down/pull/29
