### ISSUE TITLE
ScrollView within itemFull not responding

### ISSUE THREAD

**Issue by marioskonstantinou12** [react-native-vietnam/react-native-swipe-up-down#2]
ScrollView within itemFull, does not respond i.e. scroll gesture does not work as expected and itemMini is shown. Would it be possible to pass a prop to itemFull which allows gestures in children of itemFull? I've had a look at [this known issue](https://github.com/facebook/react-native/issues/1046) , not sure how well it can help.

**Comment by minhchienwikipedia** [comment]
Thank for sending me your link to know the issue. I have a solution for you to resolve this issue. 
We have props 
```
        onShowMini={() => console.log('mini')}
	onShowFull={() => console.log('full')}
	onMoveDown={() => console.log('down')}
	onMoveUp={() => console.log('up')}
```
And we can use this to handle scrollview. 
You can use like this.
```
        onShowMini={() => this.scrollView.setNativeProps({ scrollEnabled: false }}
	onShowFull={() => this.scrollView.setNativeProps({ scrollEnabled: false }}
	onMoveDown={() => this.scrollView.setNativeProps({ scrollEnabled: true }}
	onMoveUp={() => this.scrollView.setNativeProps({ scrollEnabled: true }}
```
And we can get ref from Scrollview `<ScrollView ref={(c) => { this.scrollView = c; }} >`

**Comment by huy-lv** [comment]
@minhchienwikipedia  i tried what you say but it doesnt work. please help or give me a snack example. thank you

**Comment by benov84** [comment]
not working! very dissapointed of this library
