### ISSUE TITLE
'showMini' function wasn't available

### ISSUE THREAD

**Issue by vetrivendhan48** [react-native-vietnam/react-native-swipe-up-down#27]
In my component I can't access the showMini function from the 'swipeUpDown' ref.

**Comment by vetrivendhan48** [comment]
https://github.com/react-native-vietnam/react-native-swipe-up-down/pull/26#issue-350713265

**Comment by minhchienwikipedia** [comment]
I had merged (#26 ) already. Any issue you can re-open anytime! Thanks!
