### ISSUE TITLE
How to limit the height when its shows itemfull?

### ISSUE THREAD

**Issue by schmem55** [react-native-vietnam/react-native-swipe-up-down#28]
i would like to know when its swiped up , how to limit the height not to the entire screen but only a limited height(from the bottm to HEIGHT)

thank you

**Comment by tayguohong** [comment]
I am facing this issue too, any updates?

**Comment by Luckygirlllll** [comment]
I have the same problem, did you find a solution?

**Comment by luizcoelhoc1** [comment]
if i want 80% i just replace this lines this on showFull() function
```
    this.customStyle.style.top = 0;
    this.customStyle.style.height = DEVICE_HEIGHT;
```
for this
```
    this.customStyle.style.top = DEVICE_HEIGHT*0.2;
    this.customStyle.style.height = DEVICE_HEIGHT*0.8;
```

**Comment by minhchienwikipedia** [comment]
Let's use the latest version and pass value to prop `extraMarginTop`
How it works it the lib: `DEVICE_HEIGHT - extraMarginTop`
