### ISSUE TITLE
itemFull component gets hidden on swipe-down

### ISSUE THREAD

**Issue by hazeeb** [react-native-vietnam/react-native-swipe-up-down#3]
This is my code
```
<SwipeUpDown
  swipeHeight={20}
  hasRef={ref => (this.swipeUpDownRef = ref)}
  itemFull={<Destination />}
  disablePressToShow={false}
  style={{ zIndex: 10, backgroundColor: '#a3a3a3'' }}
   animation="easeInEaseOut"
/>
```
Step 1: Swipe Up
![simulator screen shot - iphone 6 - 2018-09-04 at 19 43 00](https://user-images.githubusercontent.com/13180402/45036887-429f4400-b07b-11e8-87c1-a4105b8fe71e.png)

When i try to swipe down, the content/component gets hidden and displays only the background color.
 
![simulator screen shot - iphone 6 - 2018-09-04 at 19 43 04](https://user-images.githubusercontent.com/13180402/45036753-f3591380-b07a-11e8-8c85-149806ae04e8.png)

**What I'm trying to achieve ?**
Component shouldn't hide on swipe down.

**Comment by crock** [comment]
This is still an issue, does the author ever plan on fixing this?

**Comment by crock** [comment]
Found the solution. In `index.js`, set the line beginning with `this.customStyle.style.top` equal to 0 in both the call to `showFull()` and `showMini()`.

```js
this.customStyle.style.top = 0;
```

**Comment by minhchienwikipedia** [comment]
@hazeeb Did you try solution of @crock ?

**Comment by nitinkumar24** [comment]
@hazeeb Check after removing this line in onPanResponderMove method.      
**!this.state.collapsed && this.setState({ collapsed: true });**

**Comment by Geeta21Khati** [comment]
@nitinkumar24 It's not working. Any other solution for this

**Comment by Geeta21Khati** [comment]
@minhchienwikipedia  I tried @crock solution. No luck. Still having same issue

**Comment by IsharaHansaka** [comment]
@hazeeb did you try swipeHeight={100} ? this worked for me.

**Comment by sunilmishra** [comment]
Just add this line in showMini function.
this.SWIPE_HEIGHT = 150; // Avoid hiding when swiping down.

showMini() {
    const { onShowMini, itemMini } = this.props;
    **this.SWIPE_HEIGHT = 150; // Avoid hiding when swiping down.**
    this.customStyle.style.top = itemMini ? DEVICE_HEIGHT - this.SWIPE_HEIGHT : DEVICE_HEIGHT;
    this.customStyle.style.height = itemMini ? this.SWIPE_HEIGHT : 0;
    this.swipeIconRef && this.swipeIconRef.setState({ showIcon: false });
    this.updateNativeProps();
    !this.state.collapsed && this.setState({ collapsed: true });
    this.checkCollapsed = true;
    onShowMini && onShowMini();
  }

**Comment by imdhemy** [comment]
I think that the `MARGIN_TOP` constant on the top of the file on `src/index` is the source of this problem. My suggestion is to subtract it from `DEVICE_HEIGHT` on the `showMini()` method.

```javascript
showMini() {
    const { onShowMini, itemMini } = this.props;
    this.customStyle.style.top = itemMini
      ? DEVICE_HEIGHT - this.SWIPE_HEIGHT - MARGIN_TOP // avoid hiding on swipe down
      : DEVICE_HEIGHT;
    this.customStyle.style.height = itemMini ? this.SWIPE_HEIGHT : 0;
    this.swipeIconRef && this.swipeIconRef.setState({ showIcon: true });
    this.updateNativeProps();
    !this.state.collapsed && this.setState({ collapsed: true });
    this.checkCollapsed = true;
    onShowMini && onShowMini();
  }
```
