### ISSUE TITLE
how to close this swipeupdown component by code

### ISSUE THREAD

**Issue by raindev32** [react-native-vietnam/react-native-swipe-up-down#39]
I want to ask how to get hide of this swipe component when the user selects an item ..

Thanks in advance.

**Comment by minhchienwikipedia** [comment]
@raindev32 Let's try the latest version and see how it works in README
https://github.com/react-native-vietnam/react-native-swipe-up-down/releases/tag/v1.1.4

**Comment by bm181354** [comment]
@minhchienwikipedia Hey dude, going through the code.
Close function is bit buggy, I think. I was not able to remove the full screen. 
I followed your instruction and went through the example:
```
  itemMini={(show) => (
            <View
              style={{
                alignItems: "center",
                flex: 1,
                backgroundColor: "green",
              }}
            >
              <Text onPress={show}>This is the mini view, swipe up!</Text>
            </View>
          )}
```
After button smashing the button could be trigger and full view will be closed. However, that is no ideal. You don't want to press 20 times to get 1 click. I don't have mini view and only have full View on my setup. My guess is that there seem to be conflict on onPress function.
Appreciate the hard work dude!!

**Comment by bm181354** [comment]
Code*
```
    itemFull={(close) => {
            return (
              <View
                style={{
                  flex: 1,
                  justifyContent: "center",
                  backgroundColor: "red",
                }}
              >
                <Text onPress={close} style={styles.instructions}>
                  Swipe down to close
                </Text>
              </View>
            );
          }}
```

**Comment by minhchienwikipedia** [comment]
@bm181354 sorry, I can't get it, can you send me your full code or a video of the issue you're getting?

**Comment by bm181354** [comment]
@minhchienwikipedia  https://snack.expo.dev/@biken/modal-popover
iPhone 7 with IOS 14.7.1 seems to have a problem.
However, it works in iphone Xs (Bigger iphones).

**Comment by bm181354** [comment]
@minhchienwikipedia Some additional detail. On older iPhone model, it appears that onPress on any child view of `itemFull` is being mostly unable to click. On console it says `full screen` [this is coming from module and not from my side] while pressing any button. Honestly thinking it's a conflict somewhere in the code. Again the code works in iPhone X and higher modal.
