### ISSUE TITLE
Unexpected token, expected ";" (18: 5)

### ISSUE THREAD

**Issue by denis-hik** [react-native-vietnam/react-native-swipe-up-down#40]
./node_modules/react-native-swipe-up-down/src/index.js
SyntaxError: C:\Users\dtyus\WebstormProjects\untitled\my_mini_app\node_modules\react-native-swipe-up-down\src\index.js: Unexpected token, expected ";" (18:
5)

  16 | const MARGIN_TOP = Platform.OS === 'ios' ? 20 : 0;
  17 | const DEVICE_HEIGHT = Dimensions.get('window').height - MARGIN_TOP;
> 18 | type Props = {
     |      ^
  19 |   hasRef?: () => void,
  20 |   swipeHeight?: number,
  21 |   itemMini?: object,

**Comment by minhchienwikipedia** [comment]
@denis-hik  It's fixed, let's check the latest version
