### ISSUE TITLE
TouchableOpacity in itemFull props has no response

### ISSUE THREAD

**Issue by chenyaw0728** [react-native-vietnam/react-native-swipe-up-down#47]
I try add a touch response inside itemFull, but it is not response. Below is my code : 
<SwipeUpDown
        itemMini={<View><Text>Header</Text></View>}
        itemFull={()=><View><TouchableOpacity onPress={()=>alert("test")}><Text>Click Me</Text></TouchableOpacity></View>}   
        animation="easeInEaseOut"
        disableSwipeIcon={true} 
        iconColor='yellow'
        iconSize={30}
        style={{ backgroundColor: 'red',zIndex:0 }} // style for swipe 
      />
it look like is issue on PanResponder. anyone face this issue also?

**Comment by Ramxnchv** [comment]
Try using Pressable with onPressOut instead of onPress. It worked for me

**Comment by minhchienwikipedia** [comment]
@chenyaw0728 which React Native version you're using?

**Comment by minhchienwikipedia** [comment]
Dont have any response, I'll close this issue, feel free to open it if you still getting this issue!
