### ISSUE TITLE
Prop ref does not exist in this component

### ISSUE THREAD

**Issue by Ramxnchv** [react-native-vietnam/react-native-swipe-up-down#48]
Hello, im facing an issue when trying to open the swipe up using showFull(). 
The component does not have a ref prop (because it is exported as a function) so i can't get an instance of it to call showFull(). 
Can anyone help me?

![image](https://user-images.githubusercontent.com/38292919/162272866-e347f588-c80a-4576-918d-5238c9be6054.png)

**Comment by minhchienwikipedia** [comment]
Hi @Ramxnchv , I just fix it and release [a new version](https://github.com/react-native-vietnam/react-native-swipe-up-down/releases/tag/v1.2.0), please upgrade and check it again

**Comment by Ramxnchv** [comment]
It works now, thank you!
