### ISSUE TITLE
Change ItemFull and itemMini height

### ISSUE THREAD

**Issue by Cesar7123** [react-native-vietnam/react-native-swipe-up-down#5]
How do i change the height of my itemFull and itemMini

**Comment by jfaraklit** [comment]
You can use swipeHeight={anyvalue} . 60 is the default for mini.

**Comment by Cesar7123** [comment]
And how do I change the height of my itemFull?

**Comment by jfaraklit** [comment]
There is no a prop for that at this point but changing `MARGIN_TOP` value in the src file `index.js` will do it for you. If could fork the repo and even make it a property if you want.  I am not the author so I don't know what is his/her plans.

**Comment by Cesar7123** [comment]
Thanks that was useful for me

**Comment by DenitzOps** [comment]
In Node Modules react-native-swipe-up-down\src\index.js

line 28 add new prop examplePropName?: number
line 53 add new prop to constructor like this.NewProp = prop.examplePropName
Now go to line 124 and replace 0 with this.NewProp (this.customStyle.style.top = this.NewProp)
Now you can use your new prop in your component, define like examplePropName = { 200 }
I think the author could add this would be useful 
Just remember :) you have to edit the plugin again every time you do npm install ;)
