### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by b5414** [react-native-vietnam/react-native-swipe-up-down#50]
log:

```js
PS F:\github\frontend> npm install react-native-swipe-up-down
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.0.0" from react-native@0.69.3
npm ERR! node_modules/react-native
npm ERR!   peer react-native@">=0.41.2" from react-native-swipe-up-down@1.2.0
npm ERR!   node_modules/react-native-swipe-up-down
npm ERR!     react-native-swipe-up-down@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See B:\User\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     B:\User\npm-cache\_logs\2022-07-28T23_42_51_897Z-debug-0.log
```

deps:

```js
"animate.css": "^4.1.1",
"axios": "^0.27.2",
"node-sass": "^7.0.1",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-query": "^4.0.0",
"react-router-dom": "^6.3.0",
"react-scripts": "5.0.1",
"react-select": "^5.4.0",
```

**Comment by minhchienwikipedia** [comment]
Seems you're using ReactJS not React Native?

**Comment by Jahanzeb009** [comment]
try with --force flag

npm install react-native-swipe-up-down --force

**Comment by Jahanzeb009** [comment]
> log:
> 
> ```js
> PS F:\github\frontend> npm install react-native-swipe-up-down
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: frontend@1.0.0
> npm ERR! Found: react@18.2.0
> npm ERR! node_modules/react
> npm ERR!   react@"^18.2.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"18.0.0" from react-native@0.69.3
> npm ERR! node_modules/react-native
> npm ERR!   peer react-native@">=0.41.2" from react-native-swipe-up-down@1.2.0
> npm ERR!   node_modules/react-native-swipe-up-down
> npm ERR!     react-native-swipe-up-down@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See B:\User\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     B:\User\npm-cache\_logs\2022-07-28T23_42_51_897Z-debug-0.log
> ```
> 
> deps:
> 
> ```js
> "animate.css": "^4.1.1",
> "axios": "^0.27.2",
> "node-sass": "^7.0.1",
> "react": "^18.2.0",
> "react-dom": "^18.2.0",
> "react-query": "^4.0.0",
> "react-router-dom": "^6.3.0",
> "react-scripts": "5.0.1",
> "react-select": "^5.4.0",
> ```

try with --force flag

`npm install react-native-swipe-up-down --force`
