### ISSUE TITLE
Strange behavior 

### ISSUE THREAD

**Issue by jfaraklit** [react-native-vietnam/react-native-swipe-up-down#6]
- `itemMini`: when adding a component inside itemmini, the content of the component is also showing up on the header area of the app. 
![image](https://user-images.githubusercontent.com/14077606/51392726-ec034580-1b03-11e9-9fdc-c7058a7a5b6a.png)

- `disablePressToShow`: Setting disablePressToShow to `true `or `false `doesn't seem to work. I would expect to only be able to pull up when set to `true` but tabing the miniItem will bring the full.

**Comment by minhchienwikipedia** [comment]
Let's check the latest version!
https://github.com/react-native-vietnam/react-native-swipe-up-down/releases/tag/v1.1.3
