### ISSUE TITLE
Lagging, animation time and click function

### ISSUE THREAD

**Issue by ajoykarmakar459** [react-native-vietnam/react-native-swipe-up-down#9]
I am developing a music player with this awesome plugin but facing some issues. There is one view for playing audio but here I have to put two views so I put the same views into itemMini and itemFull and It works great. But while opening up the views it refreshes the two views and my music started freshly and there is maybe an overlay to capture gesture event so my pause play buttons are not working. Some more problem I am facing... While debugging mode this component is lagging and not responding after a few moments it's started working smoothly and one more question is there any property to delay the animation while opening up and closing down the view? 
Thank You,
Ajoy Karmakar

**Comment by DavitVosk** [comment]
Hi @ajoykarmakar459. Could you find answers to your questions? In swiper I also have button and sometimes that button pressing does not work...

**Comment by DavitVosk** [comment]
ok @ajoykarmakar459, I guess I could find which code blocks my touchable sometimes. So in `index.js` component there is `onMoveShouldSetPanResponder`, which is set `true` as default. But when `dx` and `dy` are not `0`, then it should be `false`

`const {dx, dy} = gestureState;`
 
 `if (dx!==0 && dy!==0 && dy/dx!==Math.abs(0) && dy/dx!==-1) {
      return true
    }else{
      return false
    }`

Hope this will fix your problem too

**Comment by MRSEREY** [comment]
@DavitVosk it worked well when i added your condition except on Samsung Note 8 and when I inspected it always return true. plz help

**Comment by DavitVosk** [comment]
@MRSEREY I had stopped with that feature including into my app yet... I had not checked it on Samsung Note 8. What I can propose to log `dx` and `dy` to understand what other condition you should add in my code so that it works as needed

**Comment by minhchienwikipedia** [comment]
Let's check the latest version!
https://github.com/react-native-vietnam/react-native-swipe-up-down/releases/tag/v1.1.3
